name: Realease version

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.FLUTTER_VERSION }}
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --split-per-abi
      - name: GH Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/*.apk
